# Generated by Django 4.2.7 on 2025-08-12 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('pliegos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='pliego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='pliegos.pliego'),
        ),
    ]
