# Generated by Django 4.2.7 on 2025-08-12 02:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pliego',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='Pliego', max_length=512)),
                ('archivo', models.FileField(upload_to='pliegos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('tipo_contrato', models.CharField(blank=True, max_length=50)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('requisitos_tecnicos', models.JSONField(blank=True, default=list)),
                ('documentos_obligatorios', models.JSONField(blank=True, default=list)),
                ('criterios_evaluacion', models.JSONField(blank=True, default=dict)),
                ('metadata_pliego', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
